CREATE TABLE IF NOT EXISTS PEOPLE (
	ID UUID PRIMARY KEY,
	APELIDO VARCHAR(32) UNIQUE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	STACK TEXT NULL
);

CREATE INDEX PEOPLE_NOME_INDEX ON PEOPLE (NOME);
CREATE INDEX PEOPLE_APELIDO_INDEX ON PEOPLE (APELIDO);
