CREATE TABLE IF NOT EXISTS PEOPLE (
	ID UUID PRIMARY KEY,
	APELIDO VARCHAR(32) UNIQUE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	STACK TEXT NULL
);

CREATE INDEX people_nome_index ON people (NOME);
CREATE INDEX people_apelido_index ON people (APELIDO);
