version: '3.4'

services:
  api01:
    build:
      context: ../../../../
      dockerfile: RinhaBackEnd/Dockerfile
  api02:
    build:
      context: ../../../../
      dockerfile: RinhaBackEnd/Dockerfile
  db:
    volumes:
      - ../../../../create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
  proxy:
    volumes:
      - ../../../../nginx.conf:/etc/nginx/nginx.conf:ro