version: '3.4'

services:
  api01: &api
    container_name: api01
    image: rinhabackend
    build:
      context: .
      dockerfile: RinhaBackEnd/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
    ports:
      - "80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.35GB'
  api02:
    <<: *api
    container_name: api02
  db:
    container_name: database
    image: 'postgres:latest'
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.9GB'
    ports:
       - 5432:5432
    environment:
       POSTGRES_USER: rinha
       POSTGRES_PASSWORD: 7653e869faa3 
       POSTGRES_DB: rinhadb
    volumes:
      - ./create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
    command: |
          postgres -c 'max_connections=1500' 
                   -c 'shared_buffers=512MB'
                   -c 'maintenance_work_mem=256MB'
                   -c 'effective_cache_size=1GB'
                   -c 'wal_buffers=64MB'
                   -c 'checkpoint_timeout=10min'
                   -c 'checkpoint_completion_target=0.9'
                   -c 'random_page_cost=4.0'
                   -c 'effective_io_concurrency=2'
                   -c 'autovacuum=on'
                   -c 'work_mem=4MB'
                   -c 'log_statement=none'
                   -c 'log_duration=off'
                   -c 'log_lock_waits=on'
                   -c 'log_error_verbosity=terse'
                   -c 'log_min_messages=panic'
                   -c 'log_min_error_statement=panic'
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.2GB'
  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.2GB'

networks:
  default:
    driver: bridge
    name: rinha